// Default services data for the quotation builder

export const servicesData = [
  {
    id: 'social-media',
    name: 'Social Media Management',
    slug: 'social-media',
    description: 'End-to-end social media strategy, content creation, design, and community management.',
    icon: 'Share2',
    category: 'social',
    base_price: 25000,
    features: [
      'Content strategy & calendar',
      'Post design & copywriting',
      'Community management',
      'Monthly analytics reports',
    ],
    deliverables: [
      '20-30 posts per month',
      '8-12 reels/videos per month',
      'Daily story management',
      'Response to comments/DMs',
    ],
    pricing_tiers: [
      {
        name: 'Starter',
        price: 25000,
        description: '1-2 platforms, 20 posts, 8 reels',
        features: ['Instagram + Facebook', '20 posts/month', '8 reels/month', 'Basic reporting'],
      },
      {
        name: 'Growth',
        price: 45000,
        description: '3 platforms, 30 posts, 12 reels',
        features: ['All platforms', '30 posts/month', '12 reels/month', 'Advanced analytics', 'Strategy calls'],
      },
      {
        name: 'Dominance',
        price: 75000,
        description: 'Full-scale management with priority support',
        features: ['All platforms', '40+ posts/month', '15+ reels/month', 'Real-time support', 'Monthly strategy deck'],
      },
    ],
    add_ons: [
      { name: 'Extra platform', price: 10000, description: 'Add another social platform', unit: 'platform' },
      { name: 'Extra reel', price: 2500, description: 'Additional reel production', unit: 'reel' },
      { name: 'Paid social ads management', price: 15000, description: '+ 10% of ad spend', unit: 'month' },
    ],
  },
  {
    id: 'performance-marketing',
    name: 'Performance Marketing & Ads',
    slug: 'performance-marketing',
    description: 'Data-driven Meta & Google ads campaigns optimized for leads, sales, and ROI.',
    icon: 'TrendingUp',
    category: 'marketing',
    base_price: 30000,
    features: [
      'Campaign strategy & setup',
      'Ad creative design',
      'A/B testing & optimization',
      'Conversion tracking setup',
      'Weekly performance reports',
    ],
    deliverables: [
      '2-4 ad campaigns per month',
      '10-15 ad creatives',
      'Landing page optimization',
      'Performance dashboard',
    ],
    pricing_tiers: [
      {
        name: 'Starter',
        price: 30000,
        description: 'For brands spending ₹30K-₹1L on ads',
        features: ['Meta or Google Ads', '2 campaigns', '10 ad creatives', 'Weekly reports'],
      },
      {
        name: 'Growth',
        price: 50000,
        description: 'For brands spending ₹1L-₹3L on ads',
        features: ['Meta + Google Ads', '4 campaigns', '15 ad creatives', 'Advanced tracking', 'Bi-weekly calls'],
      },
      {
        name: 'Scale',
        price: 80000,
        description: 'For brands spending ₹3L+ on ads',
        features: ['All platforms', 'Unlimited campaigns', '20+ ad creatives', 'Daily monitoring', 'Dedicated ads manager'],
      },
    ],
    add_ons: [
      { name: 'Additional platform', price: 20000, description: 'LinkedIn, YouTube, etc.', unit: 'platform' },
      { name: 'Landing page design', price: 15000, description: 'Custom landing page', unit: 'page' },
    ],
  },
  {
    id: 'branding',
    name: 'Branding & Identity',
    slug: 'branding',
    description: 'Complete brand identity system including logo, brand book, and visual guidelines.',
    icon: 'Palette',
    category: 'creative',
    base_price: 50000,
    features: [
      'Brand strategy workshop',
      'Logo design (3 concepts)',
      'Brand color palette',
      'Typography system',
      'Brand book (20-30 pages)',
    ],
    deliverables: [
      'Primary + secondary logos',
      'Brand guidelines document',
      'Business card design',
      'Social media templates',
    ],
    pricing_tiers: [
      {
        name: 'Essential',
        price: 50000,
        description: 'Logo + basic brand identity',
        features: ['Logo design', 'Color palette', 'Typography', 'Basic brand book'],
      },
      {
        name: 'Professional',
        price: 100000,
        description: 'Complete brand identity system',
        features: ['Full branding', 'Comprehensive brand book', 'Stationery design', 'Social media kit'],
      },
      {
        name: 'Premium',
        price: 200000,
        description: 'Full rebrand with positioning',
        features: ['Brand strategy', 'Complete identity system', 'Photography direction', 'Launch campaign'],
      },
    ],
    add_ons: [
      { name: 'Packaging design', price: 25000, description: 'Product packaging', unit: 'design' },
      { name: 'Brand photography', price: 35000, description: '4-hour shoot', unit: 'shoot' },
    ],
  },
  {
    id: 'web-design',
    name: 'Website & Landing Pages',
    slug: 'web-design',
    description: 'High-converting, responsive websites and landing pages optimized for performance.',
    icon: 'Globe',
    category: 'technical',
    base_price: 75000,
    features: [
      'Custom design (3-4 pages)',
      'Mobile responsive',
      'SEO optimized',
      'Contact forms',
      'Google Analytics setup',
    ],
    deliverables: [
      'Fully functional website',
      'CMS integration',
      'Performance optimization',
      'Basic SEO setup',
    ],
    pricing_tiers: [
      {
        name: 'Landing Page',
        price: 35000,
        description: 'Single high-converting page',
        features: ['1 landing page', 'Mobile responsive', 'Fast loading', 'Lead capture form'],
      },
      {
        name: 'Business Website',
        price: 75000,
        description: '5-8 page business website',
        features: ['Custom design', '5-8 pages', 'CMS integration', 'SEO basics', 'Contact forms'],
      },
      {
        name: 'E-commerce',
        price: 150000,
        description: 'Full e-commerce solution',
        features: ['Product catalog', 'Payment gateway', 'Admin panel', 'Inventory management', 'Order tracking'],
      },
    ],
    add_ons: [
      { name: 'Extra page', price: 8000, description: 'Additional website page', unit: 'page' },
      { name: 'E-commerce functionality', price: 50000, description: 'Add online store', unit: 'feature' },
      { name: 'Booking system', price: 30000, description: 'Appointment booking', unit: 'feature' },
    ],
  },
  {
    id: 'seo',
    name: 'SEO & Content Marketing',
    slug: 'seo',
    description: 'Strategic SEO and content marketing to improve rankings and drive organic traffic.',
    icon: 'Search',
    category: 'marketing',
    base_price: 30000,
    features: [
      'Keyword research',
      'On-page optimization',
      'Technical SEO audit',
      'Content strategy',
      'Monthly blog posts',
    ],
    deliverables: [
      '4-8 blog posts per month',
      'Monthly SEO reports',
      'Keyword ranking tracking',
      'Competitor analysis',
    ],
    pricing_tiers: [
      {
        name: 'Foundation',
        price: 30000,
        description: 'SEO basics + 4 blogs',
        features: ['Technical SEO audit', 'On-page optimization', '4 blog posts', 'Monthly reports'],
      },
      {
        name: 'Growth',
        price: 50000,
        description: 'Aggressive SEO + 8 blogs',
        features: ['Complete SEO', '8 blog posts', 'Link building', 'Advanced tracking', 'Strategy calls'],
      },
      {
        name: 'Dominance',
        price: 80000,
        description: 'Full content marketing engine',
        features: ['SEO mastery', '12+ blog posts', 'Guest posting', 'PR outreach', 'Content strategy deck'],
      },
    ],
    add_ons: [
      { name: 'Extra blog post', price: 5000, description: '1000-1500 words', unit: 'post' },
      { name: 'Guest post placement', price: 15000, description: 'On authority site', unit: 'post' },
    ],
  },
  {
    id: 'production',
    name: 'Photo / Video / Reels Production',
    slug: 'production',
    description: 'Professional photography, videography, and viral reel production.',
    icon: 'Video',
    category: 'creative',
    base_price: 25000,
    features: [
      'Pre-production planning',
      'Professional shoot',
      'Post-production editing',
      'Final deliverables',
    ],
    deliverables: [
      '20-30 edited photos',
      '10-15 short-form videos',
      'Raw files included',
      'Social media formats',
    ],
    pricing_tiers: [
      {
        name: 'Half-Day Shoot',
        price: 25000,
        description: '4-hour photo/video shoot',
        features: ['4 hours shooting', '20 edited photos', '5-8 reels', 'Basic editing'],
      },
      {
        name: 'Full-Day Shoot',
        price: 45000,
        description: '8-hour comprehensive shoot',
        features: ['8 hours shooting', '40 edited photos', '12-15 reels', 'Advanced editing', 'Drone shots'],
      },
      {
        name: 'Monthly Retainer',
        price: 75000,
        description: '2 shoots per month',
        features: ['2 full-day shoots', '80+ photos', '25+ reels', 'Priority scheduling', 'Creative direction'],
      },
    ],
    add_ons: [
      { name: 'Drone footage', price: 10000, description: 'Aerial photography/video', unit: 'shoot' },
      { name: 'Additional hour', price: 5000, description: 'Extra shoot time', unit: 'hour' },
      { name: 'Model/talent', price: 8000, description: 'Professional model', unit: 'model' },
    ],
  },
  {
    id: 'podcast',
    name: 'Podcast & Studio Services',
    slug: 'podcast',
    description: 'End-to-end podcast production including recording, editing, and distribution.',
    icon: 'Mic',
    category: 'creative',
    base_price: 40000,
    features: [
      'Studio recording (4 episodes)',
      'Audio editing & mastering',
      'Show notes & transcripts',
      'Distribution to platforms',
    ],
    deliverables: [
      '4 podcast episodes per month',
      'Audiograms for social',
      'Episode graphics',
      'SEO-optimized show notes',
    ],
    pricing_tiers: [
      {
        name: 'Starter',
        price: 40000,
        description: '4 episodes per month',
        features: ['Studio time', '4 episodes', 'Basic editing', 'Distribution'],
      },
      {
        name: 'Professional',
        price: 70000,
        description: '8 episodes + promotion',
        features: ['8 episodes', 'Advanced editing', 'Social promotion', 'Guest coordination'],
      },
      {
        name: 'Full Production',
        price: 120000,
        description: 'Complete podcast management',
        features: ['12+ episodes', 'Full production', 'Marketing strategy', 'Sponsorship support', 'Video podcast'],
      },
    ],
    add_ons: [
      { name: 'Video podcast', price: 20000, description: 'Video recording & editing', unit: 'episode' },
      { name: 'Extra episode', price: 8000, description: 'Additional episode', unit: 'episode' },
    ],
  },
  {
    id: 'influencer',
    name: 'Influencer Marketing',
    slug: 'influencer',
    description: 'Strategic influencer and celebrity collaborations for brand awareness and sales.',
    icon: 'Users',
    category: 'marketing',
    base_price: 50000,
    features: [
      'Influencer research & vetting',
      'Campaign strategy',
      'Negotiation & contracts',
      'Campaign management',
      'Performance reporting',
    ],
    deliverables: [
      '5-10 influencer collaborations',
      'Content approval process',
      'Performance tracking',
      'ROI analysis',
    ],
    pricing_tiers: [
      {
        name: 'Micro-Influencer',
        price: 50000,
        description: '5-10 micro-influencers',
        features: ['10K-100K followers', '5-10 influencers', 'Campaign management', 'Basic reporting'],
      },
      {
        name: 'Macro Campaign',
        price: 100000,
        description: '3-5 macro-influencers',
        features: ['100K-1M followers', '3-5 influencers', 'Comprehensive campaign', 'Advanced tracking'],
      },
      {
        name: 'Celebrity',
        price: 200000,
        description: 'Celebrity endorsement campaign',
        features: ['1M+ followers', 'Celebrity partnerships', 'Multi-platform campaign', 'PR integration'],
      },
    ],
    add_ons: [
      { name: 'Content rights', price: 25000, description: 'Usage rights for ads', unit: 'campaign' },
      { name: 'Additional influencer', price: 15000, description: 'Extra influencer', unit: 'influencer' },
    ],
  },
  {
    id: 'retainers',
    name: '360° Growth Retainers',
    slug: 'retainers',
    description: 'All-in-one retainer combining multiple services for complete brand growth.',
    icon: 'Rocket',
    category: 'strategy',
    base_price: 100000,
    features: [
      'Social media management',
      'Performance ads',
      'Content creation',
      'Monthly strategy sessions',
      'Priority support',
    ],
    deliverables: [
      'Complete digital presence',
      'Multi-channel campaigns',
      'Monthly growth reports',
      'Quarterly strategy refresh',
    ],
    pricing_tiers: [
      {
        name: 'Growth',
        price: 100000,
        description: 'Social + Ads + Content',
        features: ['Social media', 'Performance ads', 'Content creation', 'Monthly reports', '2 strategy calls/month'],
      },
      {
        name: 'Scale',
        price: 200000,
        description: 'Full digital marketing suite',
        features: ['All services', 'SEO included', 'Video production', 'Weekly check-ins', 'Dedicated strategist'],
      },
      {
        name: 'Dominance',
        price: 350000,
        description: 'Complete brand domination',
        features: ['Everything', 'Unlimited support', 'Custom campaigns', 'C-suite reporting', 'Quarterly planning sessions'],
      },
    ],
    add_ons: [
      { name: 'Website maintenance', price: 15000, description: 'Monthly updates', unit: 'month' },
      { name: 'Additional shoot day', price: 25000, description: 'Extra production day', unit: 'day' },
    ],
  },
];

export const industriesData = [
  {
    name: 'Ayurveda & Wellness',
    slug: 'ayurveda',
    description: 'Specialized digital marketing for Ayurvedic clinics, wellness centers, and holistic health brands.',
    pain_points: [
      'Difficulty explaining complex Ayurvedic concepts to modern audiences',
      'Building trust and credibility in a skeptical market',
      'Converting social followers to actual appointments',
      'Competing with modern medical practices',
    ],
    solutions: [
      'Educational content that simplifies Ayurveda',
      'Testimonial-driven social proof campaigns',
      'Appointment-optimized ad funnels',
      'Authority-building thought leadership',
    ],
    sample_services: ['social-media', 'performance-marketing', 'seo', 'production'],
    icon: '🌿',
  },
  {
    name: 'Clinics & Hospitals',
    slug: 'healthcare',
    description: 'Digital marketing for medical clinics, hospitals, and healthcare providers.',
    pain_points: [
      'Patient acquisition in competitive markets',
      'Building online reputation and trust',
      'Managing patient reviews and feedback',
      'Compliance with healthcare advertising regulations',
    ],
    solutions: [
      'Patient-focused content marketing',
      'Google My Business optimization',
      'Reputation management systems',
      'Compliance-friendly ad campaigns',
    ],
    sample_services: ['web-design', 'seo', 'performance-marketing', 'social-media'],
    icon: '🏥',
  },
  {
    name: 'Fitness & Gyms',
    slug: 'fitness',
    description: 'Growth marketing for gyms, fitness studios, personal trainers, and wellness brands.',
    pain_points: [
      'High member churn rates',
      'Seasonal membership fluctuations',
      'Differentiating from competition',
      'Converting trials to long-term members',
    ],
    solutions: [
      'Transformation-focused content strategy',
      'Retargeting campaigns for trial members',
      'Community building initiatives',
      'Results-driven social proof',
    ],
    sample_services: ['social-media', 'production', 'performance-marketing', 'influencer'],
    icon: '💪',
  },
  {
    name: 'Education & EdTech',
    slug: 'education',
    description: 'Digital marketing for educational institutions, online courses, and EdTech platforms.',
    pain_points: [
      'High student acquisition costs',
      'Low course completion rates',
      'Building credibility for new programs',
      'Competing with free content',
    ],
    solutions: [
      'Value-first content marketing',
      'Webinar funnels and lead magnets',
      'Student success stories and testimonials',
      'Multi-touch enrollment campaigns',
    ],
    sample_services: ['performance-marketing', 'seo', 'social-media', 'web-design'],
    icon: '📚',
  },
  {
    name: 'Restaurants & Cafes',
    slug: 'food',
    description: 'Social media and marketing for restaurants, cafes, cloud kitchens, and food brands.',
    pain_points: [
      'Inconsistent foot traffic',
      'Dependency on food delivery platforms',
      'Difficulty showcasing ambiance online',
      'Seasonal revenue variations',
    ],
    solutions: [
      'Mouth-watering visual content',
      'User-generated content campaigns',
      'Local SEO and Google Maps optimization',
      'Direct ordering system integration',
    ],
    sample_services: ['social-media', 'production', 'influencer', 'web-design'],
    icon: '🍽️',
  },
  {
    name: 'Real Estate',
    slug: 'real-estate',
    description: 'Digital marketing for real estate developers, agents, and property management.',
    pain_points: [
      'Long sales cycles',
      'High-value leads are hard to generate',
      'Virtual property showcasing',
      'Building trust with high-ticket buyers',
    ],
    solutions: [
      'Virtual tour and video content',
      'Hyper-targeted ad campaigns',
      'Lead nurturing sequences',
      'Property showcase websites',
    ],
    sample_services: ['web-design', 'production', 'performance-marketing', 'social-media'],
    icon: '🏗️',
  },
  {
    name: 'Politicians & Public Figures',
    slug: 'public-figures',
    description: 'Digital presence and reputation management for politicians and public figures.',
    pain_points: [
      'Managing public perception',
      'Rapid response to news and events',
      'Building grassroots support',
      'Handling negative press and trolls',
    ],
    solutions: [
      'Strategic messaging and positioning',
      'Real-time social media management',
      'Grassroots digital campaigns',
      'Online reputation management (ORM)',
    ],
    sample_services: ['social-media', 'web-design', 'seo', 'production'],
    icon: '🎯',
  },
  {
    name: 'Local Businesses',
    slug: 'local',
    description: 'Digital marketing for local shops, services, and small businesses.',
    pain_points: [
      'Limited marketing budgets',
      'Competing with big brands',
      'No digital presence',
      'Difficulty measuring ROI',
    ],
    solutions: [
      'Cost-effective social media presence',
      'Local SEO and Google My Business',
      'Community-focused content',
      'Performance tracking dashboards',
    ],
    sample_services: ['social-media', 'web-design', 'seo', 'performance-marketing'],
    icon: '🏪',
  },
];

